### ISSUE TITLE
Mac OS Installation: Header Files Missing

### ISSUE THREAD

**Issue by peter-sattler** [tableau-mkt/node-tableau-sdk#22]
Running the build on macOS Mojave 10.14.5, I get the following error:

_../src/TableauHyperExtract.h:9:10: fatal error: 'TableauHyperExtract/TableauHyperExtract_cpp.h' file not found
#include <TableauHyperExtract/TableauHyperExtract_cpp.h>_

BUT, I see the header files here:

/Library/Frameworks/TableauHyperExtract.framework/Versions/A

Please advise.

Thank you,
Pete Sattler

**Comment by peter-sattler** [comment]
> Running the build on macOS Mojave 10.14.5, I get the following error. It seems the header files are missing in the macOS download.
> 
> Please advise.
> 
> _../src/TableauHyperExtract.h:9:10: fatal error: 'TableauHyperExtract/TableauHyperExtract_cpp.h' file not found #include <TableauHyperExtract/TableauHyperExtract_cpp.h>_
> 
> Thank you,
> Pete Sattler

**Comment by peter-sattler** [comment]
This fixed the issue:

export CXX="-I /Library/Frameworks/TableauHyperExtract.framework/Headers"
